const rawDataOfMovies = [
	{
		title: "The Shawshank Redemption",
		genre: ["Drama"],
		releaseDate: new Date("1994-10-14"),
		director: "Frank Darabont",
		cast: ["Tim Robbins", "Morgan Freeman", "Bob Gunton"],
		rating: 9.3,
		likes: 10,
		description: "Two imprisoned",
		image: "https://via.placeholder.com/150",
	},
	{
		title: "The Godfather",
		genre: ["Crime"],
		releaseDate: new Date("1972-03-24"),
		director: "Francis Ford Coppola",
		cast: ["Marlon Brando", "Al Pacino", "James Caan"],
		rating: 9.2,
		likes: 8,
		description: "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
		image: "https://via.placeholder.com/150",
	},
	{
		title: "The Dark Knight",
		genre: ["Action"],
		releaseDate: new Date("2008-07-18"),
		director: "Christopher Nolan",
		cast: ["Christian Bale", "Heath Ledger", "Aaron Eckhart"],
		rating: 9.0,
		likes: 1,
		description:
			"When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
		image: "https://via.placeholder.com/150",
	},
	{
		title: "12 Angry Men",
		genre: ["Drama"],
		releaseDate: new Date("1957-04-10"),
		director: "Sidney Lumet",
		cast: ["Henry Fonda", "Lee J. Cobb", "Martin Balsam"],
		rating: 8.9,
		likes: 16,
		description: "A jury holdout attempts to prevent a miscarriage of justice by forcing his colleagues to reconsider the evidence.",
		image: "https://via.placeholder.com/150",
	},
];
export default rawDataOfMovies;
